In [1]:
import numpy as np
import pandas as pd
import os

In [2]:
df = pd.read_excel("./dataset/B01DCYYAVA-US-Reviews-200922.xlsx")
df = df[["标题","内容"]]
df.head()

,标题,内容
0,Large bin,I placed a lb of potatoes in this bin and ther...
1,Don’t hesitate!,I love this basket. I put it in my pantry and ...
2,Basket too small,The only complaint I have about this item is i...
3,"Good, but overpriced now!",The product as described in other reviews is s...
4,Basket,I used it in my garden shed to store my onions...

In [4]:
from nltk.tokenize import RegexpTokenizer
from nltk.corpus import stopwords
from nltk.stem.porter import PorterStemmer
from nltk.tokenize import word_tokenize
from gensim import corpora, models
import gensim

In [36]:
titles = []
comments = []
df.标题.apply(lambda x:titles.append(x))
df.内容.apply(lambda x:comments.append(x))
titles = [emoji.demojize(str) for str in titles]
comments = [emoji.demojize(str) for str in comments]

In [41]:
titles_token ={}
for title in titles:
    tokenizer = RegexpTokenizer(r'\w+')
    tokens = tokenizer.tokenize(title)
    tokens = [i for i in tokens if(i.lower() not in stopwords.words('english'))]
    for token in tokens:
        if token not in titles_token:
            titles_token[token] = 1
        else:
            titles_token[token] += 1
df_titles_token = pd.DataFrame.from_dict(titles_token,orient="index",columns=["频率"]).sort_values(by="频率",ascending=False)
df_titles_token = df_titles_token[df_titles_token["频率"]>5]
df_titles_token

          频率
Great     26
Good      21
basket    21
Stars     21
great     17
Five      16
Perfect   15
Sturdy    14
size      12
Basket    10
Looks      9
expected   9
storage    9
bin        8
sturdy     8
Love       8
price      7
nice       7
Nice       7
baskets    7
buy        6
good       6
quality    6
product    6

In [42]:
comments_token ={}
for comment in comments:
    tokenizer = RegexpTokenizer(r'\w+')
    tokens = tokenizer.tokenize(comment)
    tokens = [i for i in tokens if(i.lower() not in stopwords.words('english'))]
    for token in tokens:
        if token not in comments_token:
            comments_token[token] = 1
        else:
            comments_token[token] += 1
df_comments_token = pd.DataFrame.from_dict(comments_token,orient="index",columns=["频率"]).sort_values(by="频率",ascending=False)
df_comments_token = df_comments_token[df_comments_token["频率"]>5]
df_comments_token

             频率
basket      127
small        52
great        52
size         47
baskets      47
...         ...
move          6
rolls         6
3             6
holding       6
durability    6

[186 rows x 1 columns]

In [60]:
from nltk.util import ngrams 

bigrams_titles = {}
titles_token ={}
for title in titles:
    tokenizer = RegexpTokenizer(r'\w+')
    tokens = tokenizer.tokenize(title)
    tokens = [i for i in tokens if(i.lower() not in stopwords.words('english'))]
    bigrams_t = ngrams(tokens, 2) 
    for b in bigrams_t:
        if b not in bigrams_titles:
            bigrams_titles[b] = 1
        else:
            bigrams_titles[b] += 1
    for token in tokens:
        if token not in titles_token:
            titles_token[token] = 1
        else:
            titles_token[token] += 1
df_titles_token = pd.DataFrame.from_dict(titles_token,orient="index",columns=["频率"]).sort_values(by="频率",ascending=False)
df_titles_token = df_titles_token[df_titles_token["频率"]>=5]
df_bigrams_titles = pd.DataFrame.from_dict(bigrams_titles,orient="index",columns=["频率"]).sort_values(by="频率",ascending=False)
df_bigrams_titles = df_bigrams_titles[df_bigrams_titles["频率"]>=2]

In [61]:
df_titles_token

          频率
Great     26
Good      21
basket    21
Stars     21
great     17
Five      16
Perfect   15
Sturdy    14
size      12
Basket    10
Looks      9
expected   9
storage    9
bin        8
sturdy     8
Love       8
price      7
nice       7
Nice       7
baskets    7
buy        6
good       6
quality    6
product    6
small      5
Small      5
Cute       5

In [62]:
df_bigrams_titles.head(20)

                     频率
(Five, Stars)        16
(Four, Stars)         4
(Looks, great)        4
(Good, quality)       3
(Great, product)      3
(Great, basket)       3
(Great, pantry)       2
(storage, bin)        2
(Perfect, dog)        2
(toy, basket)         2
(Works, great)        2
(light, weight)       2
(dog, toys)           2
(sturdy, basket)      2
(Smaller, expected)   2
(wire, basket)        2
(Great, buy)          2
(Perfect, size)       2
(works, great)        2
(Good, product)       2